### ISSUE TITLE
9 minutes just for pse_test.py to start 

### ISSUE THREAD

**Issue by deepseek** [zhang-linrui/PSENet-Plus#2]
@zhang-linrui 
When running `pse_test.py` it takes 9 minutes just to start detecting.

**Comment by zhang-linrui** [comment]
Did you mean that the loading process takes 9 minutes? or the whole test
loading proces takes 9 minutes?
I haven't met that problem, even running the pse_enjoy.py on Windows
Subsystem for Linux without GPU, it takes less than 10s to load model and
around 7-9s for single picture detection. I only run pse_test.py on a GPU
server, it takes less than 0.5s for single picture detection. Sorry I
really have no idea about this issue.


deepseek <notifications@github.com> 于2019年11月19日周二 上午5:05写道：

**Comment by deepseek** [comment]
When I run `pse_test.py`, it gets stuck for 9 minutes on the image below, then it starts to detect the test images quickly.
![stuck](https://user-images.githubusercontent.com/49877135/69117747-d18e5580-0aa1-11ea-8e9b-be96b4a90441.jpg)

**Comment by zhang-linrui** [comment]
It seems there is something wrong with **load_psenet** function.
My suggestion is testing this function/module separately.Set some breakpoints or print debug information to find out where it goes struck.
One possible reason is that it downloads pretrained resnet model from 'https://download.pytorch.org/models/resnet50-19c8e357.pth' for the very first time use and it takes time. However I think it will be held in your cache folder later and won't happen next time.
Anyway, this process does taka time, but won't be that long:
![test](https://user-images.githubusercontent.com/54568644/69123681-f227d100-0adc-11ea-957b-0d72c5278750.gif)
