### ISSUE TITLE
about pse code

### ISSUE THREAD

**Issue by Wc66666** [zhang-linrui/PSENet-Plus#3]
Thanks author ,what is the idea about the improvement of the post-processing algorithm, or will the improved code be released later?

**Comment by zhang-linrui** [comment]
From an algorithmic perspective, BFS is a blind search strategy. One improvement that is being validated is to use heuristic search to find the dividing line and then directly fill the segmentation area. Another approach is the KNN-style classification, but not straightforward and efficient enough. I am very willing to make those ideas and codes open source after completion.
From an engineering perspective, direct optimization of the performance of origin C++ files is done by my colleagues and may involve commercial interests, so these will not be made public.

**Comment by Wc66666** [comment]
Thank you for your reply, look forward to your improved code.

**Comment by Wc66666** [comment]
> Thanks author ,what is the idea about the improvement of the post-processing algorithm, or will the improved code be released later?
